server:
  port: 8080
  error:
    include-message: always
  shutdown: graceful

spring:
  application:
    name: policy-management
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: refresh, env, health, metrics, info, loggers, prometheus